networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./config
    depends_on:
      - redis
    networks:
      - dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - dev

