FROM python:3.13.0-slim

# Устанавливаем рабочую директорию
# WORKDIR /app

# Копируем зависимости и устанавливаем их
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код проекта
COPY . .

# Указываем Gunicorn как точку входа
# CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
CMD ["python3.13", "manage.py", "runserver", "0.0.0.0:8000"]


